Repository AMP-Organisation/AMP-WebFront, pull requests merged in 2021-05, with the labels that each got.

#14 Feat/search bar n improvment
  amp-front/src/boot/axios.js
  amp-front/src/components/IconAndTitleHeader.vue
  amp-front/src/components/Medicine.vue
  amp-front/src/layouts/MainLayout.vue
  amp-front/src/pages/DeseasePageDetails.vue
  amp-front/src/pages/Disease.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/MedicinePageDetails.vue
  amp-front/src/pages/Notifications.vue
  amp-front/src/pages/OptionTwo.vue
  amp-front/src/pages/Places.vue
  amp-front/src/pages/ProfilPage.vue
  amp-front/src/pages/Settings.vue
  amp-front/src/pages/Symptoms.vue
  amp-front/src/router/routes.js
Labels: Fix, UI update and changes, enhancement

#16 :ambulance: fix corectly the problem with the id for a medicine component
  amp-front/src/boot/axios.js
  amp-front/src/components/Medicine.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/MedicinePageDetails.vue
Labels: Fix, bug

#17 Feat/treatment pillbox
  amp-front/src/components/AddPillboxDialog.vue
  amp-front/src/components/AddTreatmentDialog.vue
  amp-front/src/components/DeletePillbox.vue
  amp-front/src/components/Medicine.vue
  amp-front/src/components/Treatment.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/Pillbox.vue
Labels: enhancement

#18 Feat/following treatment
  amp-front/package-lock.json
  amp-front/package.json
  amp-front/src/components/AddTreatmentDialog.vue
  amp-front/src/components/Medicine.vue
  amp-front/src/layouts/MainLayout.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/Notifications.vue
  amp-front/src/router/index.js
Labels: enhancement

#19 Fix/probleme medicine
  amp-front/package-lock.json
  amp-front/src/components/Medicine.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/MedicinePageDetails.vue
Labels: Fix, bug

#20 Feat/translation
  amp-front/package-lock.json
  amp-front/package.json
  amp-front/src/boot/i18n.js
  amp-front/src/components/AddPillboxDialog.vue
  amp-front/src/components/AddTreatmentDialog.vue
  amp-front/src/components/DeletePillbox.vue
  amp-front/src/components/Medicine.vue
  amp-front/src/components/Treatment.vue
  amp-front/src/i18n/en-us/index.js
  amp-front/src/i18n/index.js
  amp-front/src/layouts/MainLayout.vue
  amp-front/src/pages/Covid.vue
  amp-front/src/pages/DetailsPlace.vue
  amp-front/src/pages/Disease.vue
  amp-front/src/pages/HealthCard.vue
  amp-front/src/pages/Info.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/MedicinePageDetails.vue
  amp-front/src/pages/Notifications.vue
  amp-front/src/pages/Pillbox.vue
  amp-front/src/pages/Places.vue
  amp-front/src/pages/ProfilPage.vue
  amp-front/src/pages/Symptoms.vue
  amp-front/src/router/index.js
  amp-front/src/router/routes.js
Labels: enhancement
