Repository AMP-Organisation/AMP-WebFront, pull requests merged in 2021-06, with the labels that each got.

#21 :construction: added dockerfile
  amp-front/Dockerfile
  amp-front/package-lock.json
  amp-front/package.json
Labels: enhancement

#22 :recycle: update of the interface of the page Places.vue
  amp-front/src/boot/i18n.js
  amp-front/src/pages/Places.vue
Labels: Fix, enhancement

#23 🔀 Merge follow up imc on develop (wip)
  amp-front/src/App.vue
  amp-front/src/boot/env_str.js
  amp-front/src/boot/i18n.js
  amp-front/src/components/DisplayIMCEvol.vue
  amp-front/src/components/FacadeLineChartComponent.vue
  amp-front/src/components/LineChart.vue
  amp-front/src/pages/Disease.vue
  amp-front/src/pages/FollowUp.vue
  amp-front/src/pages/HealthCard.vue
  amp-front/src/pages/ProfilPage.vue
  amp-front/src/pages/TestChartLine.vue
  amp-front/src/router/routes.js
Labels: enhancement

#24 Feat/register improvement
  amp-front/package-lock.json
  amp-front/package.json
  amp-front/src/pages/Register.vue
  amp-front/src/router/index.js
Labels: Fix

#25 :fire: removing old icon on Info.vue + :construction: added height of…
  amp-front/package-lock.json
  amp-front/package.json
  amp-front/src/boot/i18n.js
  amp-front/src/pages/Info.vue
  amp-front/src/pages/ProfilPage.vue
Labels: enhancement

#28 🔀 develop -> main "Hello Nico :-p "
  .github/workflows/linter.yml
  .github/workflows/update_dependency.yml
  amp-front/Dockerfile
  amp-front/package-lock.json
  amp-front/package.json
  amp-front/quasar.conf.js
  amp-front/src/App.vue
  amp-front/src/assets/profile.svg
  amp-front/src/assets/virus_covid.jpg
  amp-front/src/boot/axios.js
  amp-front/src/boot/env_str.js
  amp-front/src/boot/i18n.js
  amp-front/src/components/AddDisease.vue
  amp-front/src/components/AddPillboxDialog.vue
  amp-front/src/components/AddTreatmentDialog.vue
  amp-front/src/components/DeletePillbox.vue
  amp-front/src/components/DetailsDisease.vue
  amp-front/src/components/DisplayIMCEvol.vue
  amp-front/src/components/Doughnut.vue
  amp-front/src/components/FacadeLineChartComponent.vue
  amp-front/src/components/IconAndTitleHeader.vue
  amp-front/src/components/LineChart.vue
  amp-front/src/components/Medicine.vue
  amp-front/src/components/ProgressIcon.vue
  amp-front/src/components/Treatment.vue
  amp-front/src/i18n/en-us/index.js
  amp-front/src/i18n/index.js
  amp-front/src/layouts/LoginLayout.vue
  amp-front/src/layouts/MainLayout.vue
  amp-front/src/layouts/RegisterLayout.vue
  amp-front/src/pages/Covid.vue
  amp-front/src/pages/DeseasePageDetails.vue
  amp-front/src/pages/DetailsPlace.vue
  amp-front/src/pages/Disease.vue
  amp-front/src/pages/FollowUp.vue
  amp-front/src/pages/HealthCard.vue
  amp-front/src/pages/Help.vue
  amp-front/src/pages/Index.vue
  amp-front/src/pages/Info.vue
  amp-front/src/pages/Login.vue
  amp-front/src/pages/MedicinePage.vue
  amp-front/src/pages/MedicinePageDetails.vue
  amp-front/src/pages/Notifications.vue
  amp-front/src/pages/OptionOne.vue
  amp-front/src/pages/OptionTwo.vue
  amp-front/src/pages/Pillbox.vue
  amp-front/src/pages/Places.vue
  amp-front/src/pages/ProfilPage.vue
  amp-front/src/pages/Register.vue
  amp-front/src/pages/Settings.vue
  amp-front/src/pages/Symptoms.vue
  amp-front/src/pages/TestChartLine.vue
  amp-front/src/router/index.js
  amp-front/src/router/routes.js
  amp-front/src/store/store.js
Labels: enhancement
